## Welcome to numpy 

In [2]:
import numpy as np

In [3]:
print("hello")

hello


In [4]:
myarr=np.array([[3,6,37,7]],np.int8)

In [5]:
myarr

array([[ 3,  6, 37,  7]], dtype=int8)

In [6]:
myarr[0]

array([ 3,  6, 37,  7], dtype=int8)

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int8')

# array convertion

In [18]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [20]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [22]:
listarray.size

9

In [24]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [30]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
rng=np.arange(15)

In [34]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
lspace=np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [58]:
emp=np.empty((4,6))

In [60]:
emp

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
        6.23053614e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 9.34598925e-307,
        1.42418715e-306, 1.95819401e-306, 1.37961370e-306],
       [6.23054633e-307, 9.34598926e-307, 6.89804132e-307,
        9.34598926e-307, 1.86919513e-306, 9.34604358e-307],
       [2.22522597e-306, 6.89812960e-307, 1.42419530e-306,
        9.34609790e-307, 2.22522596e-306, 0.00000000e+000]])

In [62]:
emp_like=np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [64]:
ide=np.identity(45)

In [66]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [78]:
arr2=np.arange(99)

In [80]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [82]:
arr2.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [84]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [88]:
arr2.shape

(99,)

In [90]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [92]:
ar=np.array(x)

In [94]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [96]:
ar.sum(axis=0)

array([12,  8,  9])

In [98]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [100]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [104]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [106]:
ar.ndim

2

In [108]:
ar.size

9

In [110]:
ar.nbytes

36

In [112]:
one=np.array([1,3,4,66,2])

In [114]:
one.argmax()

3

In [116]:
one.argmin()

0

In [118]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [120]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [122]:
ar.argmax()

6

In [124]:
ar.argmin()

8

In [126]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [128]:
ar2=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [130]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [132]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [134]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [136]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [140]:
ar.sum()

29

In [144]:
ar.min()

0

In [146]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [148]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [150]:
np.count_nonzero(ar)

8

In [152]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [154]:
import sys

In [156]:
py_ar=[0,4,55,2]

In [158]:
np_ar=np.array(py_ar)

In [162]:
sys.getsizeof(1) * len(py_ar)

112

In [172]:
np_ar.itemsize * np_ar.size

16

In [ ]:
np_ar.tolist()