#Importing library

In [342]:
import numpy as np

Array Attributes

In [344]:
a=np.array([1,2,3])

In [345]:
a

array([1, 2, 3])

In [346]:
type(a)

numpy.ndarray

In [347]:
a.shape

(3,)

In [348]:
a.ndim

1

In [349]:
b=np.array([[1,2,3],[4,5,6]])

In [350]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [351]:
type(b)


numpy.ndarray

In [352]:
b.shape

(2, 3)

In [353]:
b.ndim

2

In [354]:
a.dtype,b.dtype

(dtype('int32'), dtype('int32'))

In [355]:
a.size

3

In [356]:
b.nbytes

24

# Array creation

In [358]:
array1=np.array([1,3,4],dtype='int')

In [359]:
array1

array([1, 3, 4])

In [360]:
zeros1=np.zeros((2,2),dtype='float')

In [361]:
zeros1

array([[0., 0.],
       [0., 0.]])

In [362]:
ones1=np.ones((3,3),dtype='int')

In [363]:
ones1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [364]:
full1=np.full((2,3),4)

In [365]:
full1

array([[4, 4, 4],
       [4, 4, 4]])

In [366]:
full2=np.full((3,2,3),4)

In [367]:
full2

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [368]:
identity1=np.identity(4,dtype='double')

In [369]:
identity1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [370]:
eye1=np.eye(4,4,-1)

In [371]:
eye1

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [372]:
arange1=np.arange(1,10,3)


In [373]:
arange1

array([1, 4, 7])

In [374]:
linspace1=np.linspace(1,15,20)

In [375]:
linspace1

array([ 1.        ,  1.73684211,  2.47368421,  3.21052632,  3.94736842,
        4.68421053,  5.42105263,  6.15789474,  6.89473684,  7.63157895,
        8.36842105,  9.10526316,  9.84210526, 10.57894737, 11.31578947,
       12.05263158, 12.78947368, 13.52631579, 14.26315789, 15.        ])

In [376]:
linspace1.size

20

In [377]:
empty=np.empty((1,5))

In [378]:
empty

array([[0., 1., 2., 3., 4.]])

In [379]:
for i in range(5):
    empty[:,i]=i
empty    

array([[0., 1., 2., 3., 4.]])

# Array indexing and slicing

In [381]:
arr1=np.array([1,2,3,4,5])

In [382]:
print(arr1)

[1 2 3 4 5]


In [383]:
arr1[0]

1

In [384]:
arr1[-2]

4

In [385]:
arr2=np.random.randint(1,10,size=(3,4))

In [386]:
print(arr2)

[[6 8 8 7]
 [8 9 7 6]
 [9 2 1 1]]


In [387]:
arr2[0][3]

7

In [388]:
 arr2[0,3]

7

In [389]:
arr3=np.random.randint(1,20,size=(3,3,4))

In [390]:
arr3

array([[[10, 17,  1, 11],
        [11, 12, 14, 19],
        [10,  3, 19, 18]],

       [[19, 19, 14,  7],
        [14,  6,  4, 16],
        [15,  3,  4,  5]],

       [[10, 16,  4, 19],
        [12,  6,  3, 11],
        [ 2, 11,  4,  6]]])

In [391]:
arr3[2,1,1]

6

# Slicing

In [393]:
print(arr1)

[1 2 3 4 5]


In [394]:
print(arr1[1:4])

[2 3 4]


In [395]:
arr2

array([[6, 8, 8, 7],
       [8, 9, 7, 6],
       [9, 2, 1, 1]])

In [396]:
arr2[:2,1:3]

array([[8, 8],
       [9, 7]])

In [397]:
arr3

array([[[10, 17,  1, 11],
        [11, 12, 14, 19],
        [10,  3, 19, 18]],

       [[19, 19, 14,  7],
        [14,  6,  4, 16],
        [15,  3,  4,  5]],

       [[10, 16,  4, 19],
        [12,  6,  3, 11],
        [ 2, 11,  4,  6]]])

In [398]:
arr3[1:2,0:3,1:3]

array([[[19, 14],
        [ 6,  4],
        [ 3,  4]]])

# Manipilating array shapes
### 1.reshape()
### 2.resize()
### 3.flatten()
### 4. revel()
### 5. defining array shape()

### reshape

In [401]:
a=np.array([[1,2,3],[4,5,6]])

In [402]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [403]:
a.shape

(2, 3)

In [404]:
a_reshaped=np.reshape(a,(3,2))

In [405]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

#### resize()

In [407]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [408]:
a_resized=np.resize(a,(3,3))

In [409]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

#### revel

In [411]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [412]:
a1=np.random.randint(1,10,(2,3))

In [413]:
a1

array([[9, 5, 9],
       [4, 8, 3]])

In [414]:
a1_raveled=np.ravel(a1)

In [415]:
a1_raveled

array([9, 5, 9, 4, 8, 3])

In [416]:
a1_raveled.shape

(6,)

In [417]:
a1_raveled[0]=0

In [418]:
a1_raveled

array([0, 5, 9, 4, 8, 3])

In [419]:
a1

array([[0, 5, 9],
       [4, 8, 3]])

#### flatten()


In [421]:
a1

array([[0, 5, 9],
       [4, 8, 3]])

In [422]:
a1_flattened=a1.flatten()

In [423]:
a1_flattened

array([0, 5, 9, 4, 8, 3])

In [424]:
    a1_flattened[0]=100

In [425]:
a1_flattened

array([100,   5,   9,   4,   8,   3])

In [426]:
a1

array([[0, 5, 9],
       [4, 8, 3]])

### defining an array shape

In [428]:
a1

array([[0, 5, 9],
       [4, 8, 3]])

In [429]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [430]:
a1.shape=(3,2)

In [431]:
a1

array([[0, 5],
       [9, 4],
       [8, 3]])

# Stacking

## Horizontal

In [433]:
a=np.arange(1,10).reshape(3,3)

In [434]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [435]:
b=a*2

In [436]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [437]:
c=b*2

In [438]:
np.hstack((a,b,c))

array([[ 1,  2,  3,  2,  4,  6,  4,  8, 12],
       [ 4,  5,  6,  8, 10, 12, 16, 20, 24],
       [ 7,  8,  9, 14, 16, 18, 28, 32, 36]])

In [439]:
np.column_stack((a,b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [440]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

## Vertical

In [442]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [443]:
np.row_stack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [444]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Depth Stack

In [446]:
np.dstack((a,b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])