In [2]:
import numpy as np
a=[1,2,3]
myarr=np.array(a)
myarr

array([1, 2, 3])

In [3]:

n=int (input("enter size of the array"))
for i in range (n):
    val=int (input("enter number"))
    a.append(val)
myarray=np.array(a)
myarray
for i in range(myarray.size):
    print(myarray[i])
arr1=myarray[2:4]  
arr1

enter size of the array 1
enter number 1


1
2
3
1


array([3, 1])

In [4]:
a=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(a)
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b=myarr.ndim
b

2

In [6]:
myarr.shape

(3, 3)

In [7]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [8]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
arr=np.diag([1,5,3,7])
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [12]:
arr=np.random.randint(1,50,12)
print(arr.shape,arr.ndim)
arr=arr.reshape(3,4)
print(arr)
print(arr.ndim)

(12,) 1
[[19 34 29 25]
 [42 23 41 37]
 [46 37 28 47]]
2


In [13]:
arr=np.random.rand(5)
arr

array([0.81990403, 0.10566829, 0.2657337 , 0.27170333, 0.53222404])

In [14]:
arr=np.random.rand(2,3)
arr

array([[0.86460904, 0.66187064, 0.86916936],
       [0.61066492, 0.87289461, 0.40476763]])

In [15]:

arr=np.random.randn(3)
arr

array([1.48409788, 1.3002138 , 2.65448123])

In [16]:
np.random.seed(6)
arr=np.random.randint(1,100,10)
arr

array([11, 74, 85, 80, 81, 63, 26,  2, 76, 78])

In [17]:
matrix=[]
row=int(input("rows"))
col=int(input("col"))
for i in range(row):
    a=[]
    for j in range(col):
        val=int(input("value"))
        a.append(val)
    matrix.append(a)
arr=np.array(matrix)    
for i in range(row):
    for j in range(col):
        print(arr[i,j],end=" ")
    print()            
                
        

rows 1
col 1
value 1


1 


In [18]:
arr[:2,1:]

array([], shape=(1, 0), dtype=int32)

In [19]:
np.random.seed(11)
a=np.random.randint(1,500,30).reshape(6,5)
a

array([[410, 192,  81,  92, 338],
       [440, 270, 333, 162,  72],
       [339, 281, 110,  93, 177],
       [254, 417, 302, 237, 126],
       [389,  35, 141, 386, 331],
       [ 38, 232, 469,  82,  92]])

In [20]:
a[3:4,2:3]

array([[302]])

In [21]:
arr=np.arange(1,16)
arr2=np.arange(1,16)
arr
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [22]:
arr3=arr+arr2
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [23]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
a.dot(b)

array([[19, 22],
       [43, 50]])

In [24]:
np.argmax(arr3)

14

In [25]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix


array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [27]:
np.sum(matrix)

116

In [28]:
np.min(matrix,axis=1)


array([11, 13,  3])

In [29]:
np.random.shuffle(arr)
arr

array([ 3, 13,  2,  9, 11,  8,  1, 15, 14, 12,  5,  4,  7, 10,  6])

In [30]:
np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
arr=np.array([1,2,3,4,1,2,5])
np.unique(arr,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [32]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [34]:
arr2=np.random.randint(10,20,9)
arr2

array([16, 16, 10, 15, 18, 17, 10, 18, 19])

In [35]:
np.array(arr2).reshape(3,3)

array([[16, 16, 10],
       [15, 18, 17],
       [10, 18, 19]])

In [36]:
arr3=np.arange(1,11)
arr3[arr3%2==0]=0
arr3

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [37]:
arr4=np.random.rand(4,4)
arr4

array([[0.37040662, 0.72482967, 0.34418396, 0.52770975],
       [0.87016427, 0.77298345, 0.9194153 , 0.7367942 ],
       [0.59016108, 0.05045466, 0.12938629, 0.03830208],
       [0.62472171, 0.02822038, 0.08221784, 0.67347501]])

In [38]:
arr5=np.arange(1,17).reshape(4,4)
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
arr5[1:,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [40]:
np.hstack((arr4,arr5))


array([[ 0.37040662,  0.72482967,  0.34418396,  0.52770975,  1.        ,
         2.        ,  3.        ,  4.        ],
       [ 0.87016427,  0.77298345,  0.9194153 ,  0.7367942 ,  5.        ,
         6.        ,  7.        ,  8.        ],
       [ 0.59016108,  0.05045466,  0.12938629,  0.03830208,  9.        ,
        10.        , 11.        , 12.        ],
       [ 0.62472171,  0.02822038,  0.08221784,  0.67347501, 13.        ,
        14.        , 15.        , 16.        ]])

In [41]:
np.vstack((arr4,arr5))


array([[ 0.37040662,  0.72482967,  0.34418396,  0.52770975],
       [ 0.87016427,  0.77298345,  0.9194153 ,  0.7367942 ],
       [ 0.59016108,  0.05045466,  0.12938629,  0.03830208],
       [ 0.62472171,  0.02822038,  0.08221784,  0.67347501],
       [ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [ 9.        , 10.        , 11.        , 12.        ],
       [13.        , 14.        , 15.        , 16.        ]])

In [42]:
%timeit [i**2 for i in range(1,11)]

2.48 μs ± 483 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [43]:
import numpy as ns
%timeit ns.arange(1,11)**2

3.57 μs ± 419 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [87]:
arr6=np.array([10,20,30,40,50,40,40])
x=np.where(arr6==40)
print(x)

(array([3, 5, 6], dtype=int64),)


In [91]:
arr7=np.array([2,5,8,9,13])
x=np.searchsorted(arr7,7)
print(x)

2
